import type { Assessment } from "@/types";

export const MOCK_ASSESSMENTS: Assessment[] = [
  {
    building: {
      id: "1", name: "Dela Cruz House", unique_code: "BHL-D1-001",
      address: "Manga District, Tagbilaran City, Bohol",
      municipality: "Tagbilaran City", province: "Bohol",
      latitude: 9.6790342, longitude: 123.0277812,
      building_type: "Concrete Building", building_use: "Commercial, Residential",
      year_built: 1942, number_of_floors: 2,
    },
    hazard: {
      building_id: "1", earthquake_intensity: "VII",
      fault_distance_km: 9.71, fault_name: "East Bohol Fault",
      seismic_source_type: 7.0, potential_liquefaction: "Safe",
      basic_wind_speed_kph: 260, terrain: "Minimal Obstruction",
      flood_susceptibility: "Low Susceptibility", storm_surge_height: "1.0 m- 2.0 m",
      slope_degrees: "1-8 degrees", elevation_m: 17.93,
      distance_to_water_m: 518.7, surface_runoff: "Concrete",
      base_height: "Same Level", drainage_system: "No Drainage System",
    },
    vulnerability: {
      building_id: "1", building_code: "Pre-Code (before 1972)",
      plan_irregularity: "Rectangular", vertical_irregularity: "No vertical irregularity",
      building_proximity: "No adjacent buildings", number_of_stories: 2,
      structural_material: "Reinforced Concrete", number_of_bays: 3,
      column_spacing_m: 4.2, building_enclosure: "Partially Open",
      wall_material: "Reinforced Concrete", structural_framing_type: "Ordinary Frame",
      flooring_material: "Concrete", maximum_crack: "-",
      uneven_settlement: false, beam_column_deformations: false,
      finishing_condition: false, decay_of_structural_member: false,
      additional_loads: false, roof_design: "Hip",
      roof_slope: "below 30 degrees", roofing_material: "Galvanized Iron Sheets",
      roof_fastener: "Metal Screw", roof_fastener_distance_mm: 300,
    },
    exposure: {
      building_id: "1",
      b11: 2, b12: 2, b13: 2, b14: 2,
      b21: 2, b22: 2, b23: 2, b24: 2, b25: 2,
      b31: 2, b32: 2, b33: 2, b34: 2,
      b41: 2, b42: 2, b43: 2, b44: 2,
    },
    result: {
      building_id: "1", risk_index: 3.25, risk_description: "LOW RISK",
      hazard_rating: 16, vulnerability_rating: 10, exposure_rating: 3, risk_rating: 29,
      narrative: "The Dela Cruz House shows relatively stable structural conditions. Minor surface weathering is observed on exterior walls, but core structural members remain intact. Its elevated ground level provides modest flood protection. The proximity to the nearest fault line is within moderate range, and no restoration urgency is noted at this time.",
      ai_course_of_action: "1. Schedule a detailed structural inspection within 12 months to monitor crack progression.\n2. Apply waterproof sealants to exterior surfaces to prevent moisture ingress.\n3. Maintain existing drainage systems and clear surrounding vegetation regularly.\n4. Document and register the property with NHCP for cultural heritage protection.",
    },
  },
  {
    building: {
      id: "2", name: "Baler House", unique_code: "BHL-D1-002",
      address: "Poblacion, Baclayon, Bohol",
      municipality: "Baclayon", province: "Bohol",
      latitude: 9.5852112, longitude: 123.2409554,
      building_type: "Timber Building", building_use: "Residential",
      year_built: 1800, number_of_floors: 2,
    },
    hazard: {
      building_id: "2", earthquake_intensity: "VII",
      fault_distance_km: 10.25, fault_name: "East Bohol Fault",
      seismic_source_type: 7.0, potential_liquefaction: "Highly Susceptible",
      basic_wind_speed_kph: 260, terrain: "Numerous Obstruction",
      slope_degrees: "1-8 degrees", elevation_m: 9.75,
      distance_to_water_m: 160.18, surface_runoff: "Grass/Soil",
      base_height: "Same Level", drainage_system: "No Drainage System",
    },
    vulnerability: {
      building_id: "2", building_code: "Pre-Code (before 1972)",
      plan_irregularity: "Irregular Shaped", vertical_irregularity: "1 Vertical Irregularity",
      building_proximity: "below 6 inches", number_of_stories: 2,
      structural_material: "Timber Frame", number_of_bays: 2,
      column_spacing_m: 3.5, building_enclosure: "Partially Open",
      wall_material: "Wood", structural_framing_type: "Ordinary Frame",
      flooring_material: "Hardwood", maximum_crack: "3.60 mm",
      uneven_settlement: true, beam_column_deformations: true,
      finishing_condition: true, decay_of_structural_member: true,
      additional_loads: true, roof_design: "Monoslope",
      roof_slope: "below 30 degrees", roofing_material: "Thatch",
      roof_fastener: "Hazel Spars", roof_fastener_distance_mm: 500,
    },
    exposure: {
      building_id: "2",
      b11: 2, b12: 2, b13: 2, b14: 2,
      b21: 2, b22: 2, b23: 2, b24: 2, b25: 2,
      b31: 2, b32: 2, b33: 2, b34: 2,
      b41: 2, b42: 2, b43: 2, b44: 2,
    },
    result: {
      building_id: "2", risk_index: 7.92, risk_description: "HIGH RISK",
      hazard_rating: 22, vulnerability_rating: 28, exposure_rating: 4, risk_rating: 54,
      narrative: "The Baler House presents serious structural vulnerabilities. Timber columns and beams exhibit significant decay and biological deterioration. The roof structure shows deformation at connection points and fastener corrosion. Its coastal proximity amplifies typhoon exposure risk. Proximity to the East Bohol Fault contributes to elevated seismic hazard.",
      ai_course_of_action: "1. Conduct immediate emergency structural assessment by a licensed structural engineer.\n2. Restrict occupancy or limit access to structurally compromised areas.\n3. Replace or reinforce deteriorated timber columns and beams with heritage-compatible materials.\n4. Upgrade roof fastener systems to metal screws at 300mm intervals per NSCP 2015.\n5. File for priority restoration funding with NHCP or UNESCO heritage programs.",
    },
  },
  {
    building: {
      id: "3", name: "Lim House", unique_code: "BHL-D2-001",
      address: "Zamora, Talibon, Bohol",
      municipality: "Talibon", province: "Bohol",
      latitude: 10.0331642, longitude: 123.1009377,
      building_type: "Concrete Building", building_use: "Residential",
      year_built: 1908, number_of_floors: 3,
    },
    hazard: {
      building_id: "3", earthquake_intensity: "VII",
      fault_distance_km: 13.09, fault_name: "East Bohol Fault",
      seismic_source_type: 7.0, potential_liquefaction: "Least Susceptible",
      basic_wind_speed_kph: 270, terrain: "Minimal Obstruction",
      flood_susceptibility: "Moderate Susceptibility", storm_surge_height: "2.1 m- 3.0 m",
      slope_degrees: "1-8 degrees", elevation_m: 304.4,
      distance_to_water_m: 2585.7, surface_runoff: "Grass/Concrete",
      base_height: "Same Level", drainage_system: "Open drainage system",
    },
    vulnerability: {
      building_id: "3", building_code: "Pre-Code (before 1972)",
      plan_irregularity: "L-shaped", vertical_irregularity: "No vertical irregularity",
      building_proximity: "No adjacent buildings", number_of_stories: 3,
      structural_material: "Reinforced Concrete", number_of_bays: 4,
      column_spacing_m: 4.8, building_enclosure: "Partially Open",
      wall_material: "Reinforced Concrete", structural_framing_type: "Ordinary Frame",
      flooring_material: "Concrete", maximum_crack: "1.10 mm",
      uneven_settlement: false, beam_column_deformations: true,
      finishing_condition: true, decay_of_structural_member: false,
      additional_loads: false, roof_design: "Gable",
      roof_slope: "below 30 degrees", roofing_material: "Galvanized Iron Sheets",
      roof_fastener: "Metal Screw", roof_fastener_distance_mm: 350,
    },
    exposure: {
      building_id: "3",
      b11: 2, b12: 2, b13: 2, b14: 2,
      b21: 2, b22: 2, b23: 2, b24: 2, b25: 2,
      b31: 2, b32: 2, b33: 2, b34: 2,
      b41: 2, b42: 2, b43: 2, b44: 2,
    },
    result: {
      building_id: "3", risk_index: 5.65, risk_description: "MODERATE RISK",
      hazard_rating: 17, vulnerability_rating: 18, exposure_rating: 4, risk_rating: 39,
      narrative: "The Lim House is a well-preserved three-storey concrete structure with moderate risk. Beam and column deformation has been observed in upper floors. Finishing conditions are deteriorating, and surface erosion is evident. Wind speed levels in the area require attention to roof integrity.",
      ai_course_of_action: "1. Perform a comprehensive structural audit focusing on beam-column connections.\n2. Restore finishing layers to prevent concrete carbonation and rebar corrosion.\n3. Inspect and reinforce the roof structure at eave connections and ridge members.\n4. Consult with a heritage architect before undertaking major restoration work.",
    },
  },
  {
    building: {
      id: "4", name: "Bato House", unique_code: "BHL-D2-002",
      address: "San Jose, Talibon, Bohol",
      municipality: "Talibon", province: "Bohol",
      latitude: 10.0472231, longitude: 123.1032112,
      building_type: "Concrete Building", building_use: "Residential",
      year_built: 1915, number_of_floors: 2,
    },
    hazard: {
      building_id: "4", earthquake_intensity: "VII",
      fault_distance_km: 12.82, fault_name: "East Bohol Fault",
      seismic_source_type: 7.0, potential_liquefaction: "Moderately Susceptible",
      basic_wind_speed_kph: 270, terrain: "Numerous Obstruction",
      slope_degrees: "1-8 degrees", elevation_m: 5.96,
      distance_to_water_m: 40.63, surface_runoff: "Grass/Concrete",
      base_height: "Same Level", drainage_system: "No Drainage System",
    },
    vulnerability: {
      building_id: "4", building_code: "Pre-Code (before 1972)",
      plan_irregularity: "Rectangular", vertical_irregularity: "No vertical irregularity",
      building_proximity: "6 inches and above", number_of_stories: 2,
      structural_material: "Reinforced Concrete", number_of_bays: 3,
      column_spacing_m: 4.0, building_enclosure: "Partially Open",
      wall_material: "Reinforced Concrete", structural_framing_type: "Ordinary Frame",
      flooring_material: "Concrete", maximum_crack: "-",
      uneven_settlement: false, beam_column_deformations: false,
      finishing_condition: true, decay_of_structural_member: true,
      additional_loads: false, roof_design: "Hip",
      roof_slope: "below 30 degrees", roofing_material: "Galvanized Iron Sheets",
      roof_fastener: "Nails", roof_fastener_distance_mm: 375,
    },
    exposure: {
      building_id: "4",
      b11: 2, b12: 2, b13: 2, b14: 2,
      b21: 2, b22: 2, b23: 2, b24: 2, b25: 2,
      b31: 2, b32: 2, b33: 2, b34: 2,
      b41: 2, b42: 2, b43: 2, b44: 2,
    },
    result: {
      building_id: "4", risk_index: 4.85, risk_description: "MODERATE RISK",
      hazard_rating: 19, vulnerability_rating: 16, exposure_rating: 3, risk_rating: 38,
      narrative: "The Bato House is a concrete ancestral home with moderate structural risk. Observations indicate deteriorating finishes and early-stage concrete spalling. The building is in a low-elevation coastal zone which raises flood risk. No significant seismic damage history on record, but aging concrete requires intervention.",
      ai_course_of_action: "1. Apply structural patch repairs to areas of concrete spalling and exposed reinforcement.\n2. Conduct biennial structural monitoring with photographic documentation.\n3. Review and improve drainage around the building perimeter.\n4. Explore heritage tax incentives or grants to fund restoration activities.",
    },
  },
  {
    building: {
      id: "5", name: "Manaloto House", unique_code: "BHL-D1-003",
      address: "Ubujan District, Tagbilaran City, Bohol",
      municipality: "Tagbilaran City", province: "Bohol",
      latitude: 9.6798322, longitude: 123.027889,
      building_type: "Concrete Building", building_use: "Residential",
      year_built: 1915, number_of_floors: 2,
    },
    hazard: {
      building_id: "5", earthquake_intensity: "VII",
      fault_distance_km: 12.82, fault_name: "East Bohol Fault",
      seismic_source_type: 7.0, potential_liquefaction: "Highly Susceptible",
      basic_wind_speed_kph: 260, terrain: "Minimal Obstruction",
      flood_susceptibility: "Low Susceptibility", storm_surge_height: "1.0 m- 2.0 m",
      slope_degrees: "1-8 degrees", elevation_m: 12.4,
      distance_to_water_m: 95.0, surface_runoff: "Concrete",
      base_height: "Same Level", drainage_system: "No Drainage System",
    },
    vulnerability: {
      building_id: "5", building_code: "Pre-Code (before 1972)",
      plan_irregularity: "T- shaped", vertical_irregularity: "1 Vertical Irregularity",
      building_proximity: "below 6 inches", number_of_stories: 2,
      structural_material: "Reinforced Concrete", number_of_bays: 3,
      column_spacing_m: 3.8, building_enclosure: "Partially Open",
      wall_material: "Reinforced Concrete", structural_framing_type: "Ordinary Frame",
      flooring_material: "Concrete", maximum_crack: "3.20 mm",
      uneven_settlement: true, beam_column_deformations: true,
      finishing_condition: true, decay_of_structural_member: true,
      additional_loads: true, roof_design: "Monoslope",
      roof_slope: "below 30 degrees", roofing_material: "Galvanized Iron Sheets",
      roof_fastener: "Nails", roof_fastener_distance_mm: 450,
    },
    exposure: {
      building_id: "5",
      b11: 2, b12: 2, b13: 2, b14: 2,
      b21: 2, b22: 2, b23: 2, b24: 2, b25: 2,
      b31: 2, b32: 2, b33: 2, b34: 2,
      b41: 2, b42: 2, b43: 2, b44: 2,
    },
    result: {
      building_id: "5", risk_index: 8.10, risk_description: "HIGH RISK",
      hazard_rating: 21, vulnerability_rating: 27, exposure_rating: 5, risk_rating: 53,
      narrative: "The Manaloto House is classified as high risk. Significant deterioration of columns and beams has been documented. The roof features a monoslope design with large fastener spacing particularly vulnerable to typhoon-force winds. The structure is near the East Bohol Fault, and no restoration efforts have been initiated.",
      ai_course_of_action: "1. Issue a formal structural risk notice to the building owner and local government.\n2. Immediately secure unstable structural members using temporary shoring.\n3. Commission a licensed structural engineer for a full structural rehabilitation plan.\n4. Replace the roof system entirely using metal screw fasteners at 300mm intervals.\n5. Submit for inclusion in NHCP Priority Heritage Restoration Program.",
    },
  },
  {
    building: {
      id: "6", name: "Sulague House", unique_code: "BHL-D2-003",
      address: "San Isidro, Talibon, Bohol",
      municipality: "Talibon", province: "Bohol",
      latitude: 10.0484421, longitude: 123.1173216,
      building_type: "Timber Building", building_use: "Commercial and Residential",
      year_built: 1922, number_of_floors: 2,
    },
    hazard: {
      building_id: "6", earthquake_intensity: "VII",
      fault_distance_km: 12.70, fault_name: "East Bohol Fault",
      seismic_source_type: 7.0, potential_liquefaction: "Safe",
      basic_wind_speed_kph: 270, terrain: "Numerous Obstruction",
      slope_degrees: "1-8 degrees", elevation_m: 98.32,
      distance_to_water_m: 3326.68, surface_runoff: "Concrete",
      base_height: "Base is higher", drainage_system: "Closed drainage system",
    },
    vulnerability: {
      building_id: "6", building_code: "Pre-Code (before 1972)",
      plan_irregularity: "Rectangular", vertical_irregularity: "No vertical irregularity",
      building_proximity: "No adjacent buildings", number_of_stories: 2,
      structural_material: "Timber Frame", number_of_bays: 2,
      column_spacing_m: 3.5, building_enclosure: "Partially Open",
      wall_material: "Wood", structural_framing_type: "Ordinary Frame",
      flooring_material: "Hardwood", maximum_crack: "-",
      uneven_settlement: false, beam_column_deformations: false,
      finishing_condition: false, decay_of_structural_member: false,
      additional_loads: false, roof_design: "Dutch Hip",
      roof_slope: "below 30 degrees", roofing_material: "Galvanized Iron Sheets",
      roof_fastener: "Metal Screw", roof_fastener_distance_mm: 300,
    },
    exposure: {
      building_id: "6",
      b11: 2, b12: 2, b13: 2, b14: 2,
      b21: 2, b22: 2, b23: 2, b24: 2, b25: 2,
      b31: 2, b32: 2, b33: 2, b34: 2,
      b41: 2, b42: 2, b43: 2, b44: 2,
    },
    result: {
      building_id: "6", risk_index: 2.33, risk_description: "LOW RISK",
      hazard_rating: 14, vulnerability_rating: 11, exposure_rating: 3, risk_rating: 28,
      narrative: "The Sulague House is in remarkably good condition relative to its age. The timber framing shows minimal decay and finishing is well-maintained. The structure sits in a safe elevation zone with no flood or earthquake damage history. Community involvement in its upkeep has been a significant factor in its preservation.",
      ai_course_of_action: "1. Maintain current conservation practices and document routine maintenance activities.\n2. Apply wood preservative treatments every 3–5 years to prevent biological deterioration.\n3. Develop a community-led heritage stewardship plan to sustain current maintenance levels.\n4. Nominate for heritage recognition to enhance protection and attract preservation funding.",
    },
  },
];

export function getStats() {
  const total = MOCK_ASSESSMENTS.length;
  const low = MOCK_ASSESSMENTS.filter(a => a.result.risk_description === "LOW RISK").length;
  const mod = MOCK_ASSESSMENTS.filter(a => a.result.risk_description === "MODERATE RISK").length;
  const high = MOCK_ASSESSMENTS.filter(a => a.result.risk_description === "HIGH RISK").length;
  return { total, low, mod, high };
}
a.result.risk_description === "HIGH RISK").length;
  return { total, low, mod, high };
}
